import prisma from "@/config/prisma";
import { Session } from "@/generated/prisma";
import { SessionValidationResult } from "@/types/session";
import { sha256 } from "@oslojs/crypto/sha2";
import {
  encodeBase32LowerCaseNoPadding,
  encodeHexLowerCase,
} from "@oslojs/encoding";

/**
 * Generates a session token of 20 bytes
 * @returns the new random token generated
 */
export const generateSessionToken = (): string => {
  // 20 bytes = 20 * 8 bits
  const bytes = new Uint8Array(20);
  // use crypto lib to get a random value of 20 bytes
  crypto.getRandomValues(bytes);
  // base 32 encode it so -> (20 bytes * 8 bits) / 5 = 32 characters, so encode function converts 5 bits to 1 character
  const token = encodeBase32LowerCaseNoPadding(bytes);
  // return the token
  return token;
};

/**
 * Generate a refresh token
 * @returns the new refresh token
 */
export const generateRefreshToken = (): string => {
  // 20 bytes = 20 * 8 bits
  const bytes = new Uint8Array(20);
  // use crypto lib to get a random value of 20 bytes
  crypto.getRandomValues(bytes);
  // base 32 encode it so -> (20 bytes * 8 bits) / 5 = 32 characters, so encode function converts 5 bits to 1 character
  const token = encodeBase32LowerCaseNoPadding(bytes);
  // return the token
  return token;
};

/**
 * Create a new session for user
 * @param token - the token generated by above methods
 * @param userId - the user id of user trying to login
 * @returns the new session for the user
 */
export const createSession = async (
  token: string,
  userId: string,
): Promise<Session> => {
  // generate a new session Id from token - sha256 is deterministic algo so we'll get same sessionId for same token always
  const sessionId = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));
  // prepare the payload
  const data: Omit<Session, "id" | "createdAt" | "updatedAt"> = {
    sessionId,
    userId,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30), // Set expiration date of session to 30 days from now
  };
  // Create session
  const session = await prisma.session.create({
    data,
  });
  return session;
};

/**
 * Check if the token and session is valid
 * @param token - the token that we used to create the session
 * @returns - the session and user or even null if session does not exists
 */
export const validateSessionToken = async (
  token: string,
): Promise<SessionValidationResult> => {
  // get the session id from token - sha256 is deterministic algo so we'll get same sessionId for same token always
  // which means if we a session exists which uses a session id that was created using the token above then we'll be able to find that session
  const sessionId = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));
  // find the session based on sessionId
  const result = await prisma.session.findUnique({
    where: {
      sessionId,
    },
    // Include the following fields in the response
    include: {
      user: {
        include: {
          customerProfile: {
            include: { addresses: { where: { active: true, primary: true } } },
          },
          vendorProfile: true,
          role: true,
        },
      },
    },
  });
  // return null if session not found meaning wrong or invalid token
  if (result === null) {
    return { session: null, user: null };
  }

  // get the user and session from results
  const { user, ...session } = result;
  // delete if this is an expired session and return null
  if (Date.now() >= session.expiresAt.getTime()) {
    await prisma.session.delete({ where: { sessionId } });
    return { session: null, user: null };
  }

  // If session has not yet expired then refresh the session expiration date
  // 15 days before the expiration date
  if (Date.now() >= session.expiresAt.getTime() - 1000 * 60 * 60 * 24 * 15) {
    // Set new expiration date to 30 days from now
    session.expiresAt = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30);

    // Update session
    await prisma.session.update({
      where: {
        sessionId: session.id,
      },
      data: {
        expiresAt: session.expiresAt,
      },
    });
  }
  return { session, user };
};

/**
 * forcefully remove a session and delete it
 * @param sessionId - the id of the session
 */
export const invalidateSession = async (sessionId: string): Promise<void> => {
  await prisma.session.delete({ where: { sessionId } });
};
